# Generated by Django 4.2.19 on 2025-02-13 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(1, 'Chờ xác nhận'), (2, 'Đang hoạt động'), (3, 'Tạm ngừng hoạt động'), (4, 'Đang bị khoá')], default=2)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tài khoản',
                'verbose_name_plural': 'Quản lý tài khoản',
                'db_table': 'users_user',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['username'], name='users_user_usernam_65d164_idx'), models.Index(fields=['created_by'], name='users_user_created_8bd1f9_idx'), models.Index(fields=['created_at'], name='users_user_created_cf865c_idx')],
            },
        ),
    ]
